name: Run Wealth Script and Commit HTML
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '30 16 */14 * *'  # Runs every 14 days 9:30 PM IST 

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install feedparser

    # Step 4: Run the script
    - name: Run wealth.py
      run: python wealth.py

    # Step 5: Commit and push changes
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Auto-update: Generated index.html"
        git push
